#!/bin/sh
#
# @name ALERION Hydradrone OctoCoax 8kg
#
# @url http://www.alerion.fr/nos-projets/hydradrone/
#
# @type Hydradrone
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 motor 5
# @output MAIN6 motor 6
# @output MAIN7 motor 7
# @output MAIN8 motor 8
#
# @output AUX1 lock servo
# @output AUX2 rotation servo
# @output AUX3 probe servo
#
# @maintainer Antoine Richard <antoine.richard@alerion.fr>
#

sh /etc/init.d/rc.mc_defaults

sh /etc/init.d/rc.aqua_apps

if [ $AUTOCNF = yes ]
then
# Acceptance radius
	param set NAV_ACC_RAD 2
	
# PWM value for NaN in tristate mixer of rotation servo set to 0
	param set PWM_AUX_DIS6 0

#	param set BAT_N_CELLS 4
fi

# MAV_TYPE of 14 is Octorotor, 11 is boat/ship
set MAV_TYPE 14

set MIXER hydradrone
set MIXER_AUX hydradrone

set PWM_OUT 12345678
set PWM_AUX_OUT 123
